import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, FileUp, Trash2 } from 'lucide-react'
import { useState, type ChangeEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { ApiClientError, deleteFile, downloadFile, getMyFiles, uploadFile, type StoredFileSummary } from '@/api/client'
import { PageHeader, StatusPanel } from '@/components/layout/Page'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { formatDateTime, formatFileSize } from '@/i18n/format'

export function FileManagementPage() {
  const { t } = useTranslation('files'); const { t: common } = useTranslation('common'); const queryClient = useQueryClient(); const files = useQuery({ queryKey: ['files'], queryFn: getMyFiles }); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [selected, setSelected] = useState<string | null>(null)
  const upload = useMutation({ mutationFn: uploadFile, onSuccess: async () => { setError(null); setMessage(t('uploaded')); setSelected(null); await queryClient.invalidateQueries({ queryKey: ['files'] }) }, onError: caught => setError(caught instanceof ApiClientError ? caught.message : t('uploadError')) })
  const remove = useMutation({ mutationFn: deleteFile, onSuccess: async () => { setError(null); setMessage(t('deleted')); await queryClient.invalidateQueries({ queryKey: ['files'] }) }, onError: caught => setError(caught instanceof ApiClientError ? caught.message : t('deleteError')) })
  const select = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; setMessage(null); setSelected(file?.name ?? null); if (file) upload.mutate(file); event.target.value = '' }
  const download = async (file: StoredFileSummary) => { try { const blob = await downloadFile(file.id); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = file.originalName; link.click(); URL.revokeObjectURL(url) } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : t('downloadError')) } }
  return <><PageHeader description={t('description')} eyebrow={t('eyebrow')} title={t('title')} /><Card className="mb-6"><CardHeader><CardTitle>{t('uploadTitle')}</CardTitle><CardDescription>{t('uploadDescription')}</CardDescription></CardHeader><CardContent><label className="flex min-h-32 cursor-pointer flex-col items-center justify-center gap-3 rounded-xl border border-dashed bg-muted/25 p-5 text-center hover:bg-muted/50"><FileUp className="text-primary" /><span className="text-sm font-semibold">{t('input')}</span><Input aria-label={t('input')} accept=".pdf,.png,.jpg,.jpeg,.txt" className="sr-only" disabled={upload.isPending} onChange={select} type="file" /></label>{selected && <p className="mt-3 break-all text-sm text-muted-foreground">{t('selected', { name: selected })}</p>}{upload.isPending && <p className="mt-3 text-sm" role="status">{t('uploading')}</p>}</CardContent></Card>{error && <Alert className="mb-4" variant="destructive" role="alert"><AlertDescription>{error}</AlertDescription></Alert>}{message && <Alert className="mb-4" role="status"><AlertDescription>{message}</AlertDescription></Alert>}<Card><CardHeader><CardTitle>{t('listTitle')}</CardTitle><CardDescription>{t('listDescription')}</CardDescription></CardHeader><CardContent>{files.isPending && <StatusPanel><p role="status">{t('loading')}</p></StatusPanel>}{files.isError && <Alert variant="destructive" role="alert"><AlertDescription>{t('loadError')}</AlertDescription></Alert>}{files.data?.content.length === 0 && <StatusPanel>{t('empty')}</StatusPanel>}{files.data && files.data.content.length > 0 && <div className="grid gap-3">{files.data.content.map(file => <article className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between" key={file.id}><div className="min-w-0"><p className="break-all font-semibold">{file.originalName}</p><p className="mt-1 text-xs text-muted-foreground">{formatFileSize(file.size)} · {formatDateTime(file.createdAt)}</p></div><div className="flex gap-2"><Button className="min-h-11 flex-1 sm:flex-none" onClick={() => download(file)} variant="outline"><Download />{common('download')}</Button><Button className="min-h-11 flex-1 sm:flex-none" disabled={remove.isPending} onClick={() => remove.mutate(file.id)} variant="destructive"><Trash2 />{common('remove')}</Button></div></article>)}</div>}</CardContent></Card></>
}
