import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { ApiClientError, createUser, getPermissionCatalog, getUser, getUsers, updateUserProfile, updateUserStatus, type UserSummary } from '@/api/client'
import { PageHeader, StatusPanel } from '@/components/layout/Page'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { AlertDialog } from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAuth } from '@/features/auth/model/useAuth'
import { formatDate } from '@/i18n/format'

export function UsersPage() {
  const { t } = useTranslation('users'); const users = useQuery({ queryKey: ['users'], queryFn: () => getUsers() }); const roles = useQuery({ queryKey: ['permissions'], queryFn: getPermissionCatalog }); const { user: currentUser } = useAuth(); const queryClient = useQueryClient()
  const [createError, setCreateError] = useState<string | null>(null); const [createdMessage, setCreatedMessage] = useState<string | null>(null); const [statusError, setStatusError] = useState<string | null>(null); const [editing, setEditing] = useState<UserSummary | null>(null)
  const roleOptions = roles.data?.filter(role => role.role !== 'SUPER_ADMIN' && role.enabled).map(role => ({ value: role.role, label: role.displayName || role.role })) ?? []
  const create = useMutation({ mutationFn: createUser, onSuccess: async created => { setCreatedMessage(t('created', { name: created.displayName })); await queryClient.invalidateQueries({ queryKey: ['users'] }) } })
  const changeStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'ACTIVE' | 'DISABLED' }) => updateUserStatus(id, status), onSuccess: async () => { setStatusError(null); await queryClient.invalidateQueries({ queryKey: ['users'] }) }, onError: error => setStatusError(error instanceof ApiClientError ? error.message : t('statusError')) })
  const update = useMutation({ mutationFn: ({ id, displayName, role }: { id: string; displayName: string; role: string }) => updateUserProfile(id, { displayName, role }), onSuccess: async () => { setEditing(null); setStatusError(null); await queryClient.invalidateQueries({ queryKey: ['users'] }) }, onError: error => setStatusError(error instanceof ApiClientError ? error.message : t('updateError')) })
  const startEditing = async (id: string) => { try { setEditing(await getUser(id)); setStatusError(null) } catch (error) { setStatusError(error instanceof ApiClientError ? error.message : t('loadOneError')) } }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setCreateError(null); setCreatedMessage(null); const form = event.currentTarget; const data = new FormData(form); try { await create.mutateAsync({ email: String(data.get('email')), password: String(data.get('password')), displayName: String(data.get('displayName')), role: String(data.get('role')) }); form.reset() } catch (error) { setCreateError(error instanceof ApiClientError ? error.message : t('createError')) } }
  const statusAction = (user: UserSummary) => ({ id: user.id, status: user.status === 'ACTIVE' ? 'DISABLED' as const : 'ACTIVE' as const })
  const statusLabel = (user: UserSummary) => user.status === 'ACTIVE' ? t('deactivate') : user.status === 'LOCKED' ? t('unlock') : t('activate')
  return <><PageHeader description={t('description')} eyebrow={t('eyebrow')} title={t('title')} />
    {currentUser?.permissions.includes('user:create') && <Card className="mb-6"><CardHeader><CardTitle>{t('createTitle')}</CardTitle><CardDescription>{t('createDescription')}</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><div className="grid gap-2"><label htmlFor="displayName">{t('name')}</label><Input id="displayName" name="displayName" required /></div><div className="grid gap-2"><label htmlFor="new-user-email">{t('email')}</label><Input id="new-user-email" name="email" required type="email" /></div><div className="grid gap-2"><label htmlFor="new-user-password">{t('initialPassword')}</label><Input id="new-user-password" minLength={12} name="password" required type="password" /></div><div className="grid gap-2"><label>{t('role')}</label><Select ariaLabel={t('role')} defaultValue="VIEWER" name="role" options={roleOptions} /></div>{createError && <Alert className="md:col-span-2" variant="destructive" role="alert"><AlertDescription>{createError}</AlertDescription></Alert>}{createdMessage && <Alert className="md:col-span-2" role="status"><AlertDescription>{createdMessage}</AlertDescription></Alert>}<Button className="min-h-11 md:col-span-2 md:w-fit" disabled={create.isPending} type="submit">{create.isPending ? t('creating') : t('create')}</Button></form></CardContent></Card>}
    <Card><CardHeader><CardTitle>{t('listTitle')}</CardTitle><CardDescription>{t('listDescription')}</CardDescription></CardHeader><CardContent>{statusError && <Alert className="mb-4" variant="destructive" role="alert"><AlertDescription>{statusError}</AlertDescription></Alert>}{users.isPending && <div className="grid gap-3" role="status" aria-label={t('loading')}>{[1, 2, 3].map(row => <Skeleton className="h-14 w-full" key={row} />)}</div>}{users.isError && <Alert variant="destructive" role="alert"><AlertTitle>{t('listError')}</AlertTitle><AlertDescription>{users.error instanceof ApiClientError && users.error.status === 403 ? t('forbidden') : users.error.message}</AlertDescription><Button className="mt-3" onClick={() => users.refetch()} variant="outline">다시 시도</Button></Alert>}{users.data?.content.length === 0 && <StatusPanel>{t('empty')}</StatusPanel>}
      {editing && <form className="mb-5 grid gap-3 rounded-xl border bg-muted/20 p-4 md:grid-cols-3" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ id: editing.id, displayName: String(data.get('displayName')), role: String(data.get('role')) }) }}><Input aria-label={t('editName')} defaultValue={editing.displayName} maxLength={100} name="displayName" required /><Select ariaLabel={t('editRole')} defaultValue={editing.role} name="role" options={roleOptions} /><div className="flex gap-2"><Button disabled={update.isPending} type="submit">저장</Button><Button onClick={() => setEditing(null)} type="button" variant="outline">취소</Button></div></form>}
      {users.data && users.data.content.length > 0 && <Table><TableHeader><TableRow><TableHead>{t('name')}</TableHead><TableHead>{t('email')}</TableHead><TableHead>{t('role')}</TableHead><TableHead>{t('status')}</TableHead><TableHead>{t('createdAt')}</TableHead><TableHead>{t('actions')}</TableHead></TableRow></TableHeader><TableBody>{users.data.content.map(user => <TableRow key={user.id}><TableCell className="font-medium">{user.displayName}</TableCell><TableCell>{user.email}</TableCell><TableCell><Badge variant="secondary">{user.role}</Badge></TableCell><TableCell><Badge variant={user.status === 'ACTIVE' ? 'success' : 'outline'}>{user.status}</Badge></TableCell><TableCell>{formatDate(user.createdAt)}</TableCell><TableCell>{currentUser?.permissions.includes('user:update') && currentUser.id !== user.id && <div className="flex gap-2"><Button onClick={() => startEditing(user.id)} size="sm" variant="outline">{t('editName').replace('할 이름', '')}</Button><AlertDialog actionLabel={statusLabel(user)} description={`${user.displayName} 사용자의 상태를 변경합니다.`} destructive={user.status === 'ACTIVE'} onAction={() => changeStatus.mutate(statusAction(user))} title={`${statusLabel(user)}할까요?`} trigger={<Button disabled={changeStatus.isPending} size="sm" variant="outline">{statusLabel(user)}</Button>} /></div>}</TableCell></TableRow>)}</TableBody></Table>}
    </CardContent></Card>
  </>
}
