export const ko = {
  common: {
    appName: 'INO Admin', skipToContent: '본문으로 바로가기', retry: '다시 시도', save: '저장', cancel: '취소', edit: '수정', remove: '삭제', download: '다운로드', enable: '활성화', disable: '비활성화', navigation: '주 메뉴', openMenu: '메뉴 열기', closeMenu: '메뉴 닫기', logout: '로그아웃', account: '계정', settings: '화면 설정', theme: '테마', themeLight: '라이트', themeDark: '다크', themeSystem: '시스템', empty: '표시할 항목이 없습니다.', statusNormal: '정상', statusPublic: '공개', order: '순서 {{value}}', showPassword: '입력 내용 표시', hidePassword: '입력 내용 숨기기'
  },
  auth: { eyebrow: 'SECURE ADMIN ACCESS', title: '관리자 로그인', description: '관리자 계정으로 로그인해 시스템을 관리하세요.', email: '이메일', password: '비밀번호', submit: '로그인', submitting: '로그인 중…', connectionError: '서버에 연결할 수 없습니다.', restoring: '인증 상태를 확인하는 중…' },
  dashboard: { eyebrow: 'SYSTEM OVERVIEW', title: '관리자 시작 화면', description: '서비스와 관리 기능의 현재 상태를 확인하세요.', connectionTitle: '백엔드 연결 상태', connectionDescription: '샘플 API의 현재 응답입니다.', loading: '연결 상태를 불러오는 중…', errorTitle: '연결 오류', forbidden: '이 정보를 볼 권한이 없습니다.' },
  users: { eyebrow: 'IDENTITY', title: '사용자 관리', description: '관리자 계정, 역할과 사용 상태를 관리합니다.', createTitle: '사용자 생성', createDescription: 'ADMIN 또는 VIEWER 계정을 생성합니다.', name: '이름', email: '이메일', initialPassword: '초기 비밀번호', role: '역할', create: '사용자 생성', creating: '생성 중…', created: '{{name}} 사용자를 생성했습니다.', createError: '사용자를 생성할 수 없습니다.', listTitle: '사용자 목록', listDescription: '등록된 관리자 계정과 현재 상태입니다.', loading: '사용자를 불러오는 중…', listError: '조회 오류', forbidden: '사용자 목록을 볼 권한이 없습니다.', empty: '등록된 사용자가 없습니다.', status: '상태', createdAt: '등록일', actions: '관리', editName: '수정할 이름', editRole: '수정할 역할', activate: '활성화', deactivate: '비활성화', unlock: '잠금 해제', statusError: '사용자 상태를 변경할 수 없습니다.', updateError: '사용자 정보를 변경할 수 없습니다.', loadOneError: '사용자 정보를 불러올 수 없습니다.' },
  permissions: { eyebrow: 'IDENTITY', title: '권한 카탈로그', description: '역할별 접근 권한과 사용 상태를 관리합니다.', createTitle: '커스텀 역할 생성', roleKey: '역할 키', roleName: '역할 이름', create: '역할 생성', listTitle: '역할별 권한', listDescription: 'API 접근에 사용되는 서버 권한 키입니다.', loading: '권한을 불러오는 중…', errorTitle: '조회 오류', loadError: '권한을 불러올 수 없습니다.', updateError: '권한을 변경할 수 없습니다.', empty: '부여된 권한 없음' },
  menus: { eyebrow: 'NAVIGATION', title: '메뉴 관리', description: '관리자 내비게이션의 경로, 권한과 노출 순서를 관리합니다.', createTitle: '메뉴 생성', createDescription: '경로, 아이콘 키, 권한과 정렬 순서를 등록합니다.', id: '메뉴 ID', name: '메뉴 이름', route: '경로', icon: '아이콘', parentId: '부모 메뉴 ID', permission: '필요 권한', order: '정렬 순서', add: '메뉴 추가', allTitle: '전체 메뉴', loading: '메뉴를 불러오는 중…', loadError: '메뉴를 불러올 수 없습니다.', saveError: '메뉴를 저장할 수 없습니다.', statusError: '메뉴 상태를 변경할 수 없습니다.', public: '공개 메뉴', empty: '등록된 메뉴가 없습니다.' },
  files: { eyebrow: 'STORAGE', title: '파일 관리', description: '내가 업로드한 파일을 안전하게 관리합니다.', uploadTitle: '파일 업로드', uploadDescription: 'PDF, PNG, JPEG, 텍스트 파일을 최대 10MB까지 업로드할 수 있습니다.', input: '업로드할 파일', selected: '선택한 파일: {{name}}', uploading: '업로드 중…', uploaded: '파일을 업로드했습니다.', uploadError: '파일을 업로드할 수 없습니다.', deleted: '파일을 삭제했습니다.', deleteError: '파일을 삭제할 수 없습니다.', downloadError: '파일을 다운로드할 수 없습니다.', listTitle: '내 파일', listDescription: '본인이 업로드한 파일만 표시됩니다.', loading: '파일을 불러오는 중…', loadError: '파일 목록을 불러올 수 없습니다.', empty: '업로드한 파일이 없습니다.' }
} as const
